backend:
  # name: github
  # repo: Benjamin-Bach/gridsome
  name: git-gateway
  branch: master
  local_backend:
    url: http://dev.gridsome

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content"
    media_folder: "/static/uploads"
    public_folder: "/uploads"
    # path: "{{subfolder}}/{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      # - {label: "Dossier", name: "subfolder", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "References"
        name: "refs"
        widget: "relation"
        collection: "posts"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title", "date"]