backend:
  name: github
  repo: Benjamin-Bach/gridsome

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content"
    media_folder: "/static/uploads"
    public_folder: "/uploads"
    summary: "{{title}} {{slug}}"
    # path: "{{subfolder}}/{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      # - {label: "Dossier", name: "subfolder", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "References"
        name: "refs"
        widget: "relation"
        collection: "posts"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title", "date"]
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content/pages
    create: true
    # adding a nested object will show the collection folder structure
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}--' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
  - name: "refs"
    label: "Références"
    folder: "refs"
    media_folder: ""
    public_folder: ""
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: 'Home Section'
        name: 'sections'
        widget: 'list'
        types:
          - label: 'Carousel'
            name: 'carousel'
            widget: object
            summary: '{{fields.header}}'
            fields:
              - { label: Header, name: header, widget: string, default: 'Image Gallery' }
              - { label: Template, name: template, widget: string, default: 'carousel.html' }
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
          - label: 'Spotlight'
            name: 'spotlight'
            widget: object
            fields:
              - { label: Header, name: header, widget: string, default: 'Spotlight' }
              - { label: Template, name: template, widget: string, default: 'spotlight.html' }
              - { label: Text, name: text, widget: text, default: 'Hello World' }
